services:
  web:
    build:
      context: .
    container_name: think_web
    restart: always
    environment:
      DJANGO_SECRET_KEY: change-me
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0,web
      POSTGRES_DB: think_auth
      POSTGRES_USER: think_user
      POSTGRES_PASSWORD: think_password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      JWT_SECRET_KEY: change-me
      JWT_ACCESS_TOKEN_EXPIRE_SECONDS: 1800
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: think_products
      MONGO_URI: mongodb://think_mongo_user:think_mongo_password@mongo:27017/think_products?authSource=admin
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
    networks:
      - think_network

  postgres:
    image: postgres:16
    container_name: think_postgres
    restart: always
    environment:
      POSTGRES_DB: think_auth
      POSTGRES_USER: think_user
      POSTGRES_PASSWORD: think_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - think_network

  mongo:
    image: mongo:7
    container_name: think_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: think_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: think_mongo_password
      MONGO_INITDB_DATABASE: think_products
    ports:
      - "27017:27017"
    volumes:
      - mongo_products_data:/data/db
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - think_network

volumes:
  postgres_auth_data:
  mongo_products_data:

networks:
  think_network:
    driver: bridge
